"""Track C data loading for silver XSum / CNN-DM extractive datasets.

Track C does not use ACLSum aspect labels directly. It loads silver datasets
generated from abstractive datasets using the best Track B heuristic.

Expected silver columns:
- id
- dataset
- source_sentences
- reference_summary
- silver_indices   # 1-based sentence indices
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Sequence, Union

import pandas as pd
import numpy as np

import ast
import json


_SILVER_CACHE: Dict[str, pd.DataFrame] = {}


def load_split(path: Union[str, Path]):
    """Load a Track C silver dataset.

    Unlike Track A, `path` is not 'train'/'validation'/'test'.
    It should point to a generated silver file, for example:

        data/silver/xsum_silver.parquet
        data/silver/cnndm_silver.parquet
    """
    path = str(path)
    if path not in _SILVER_CACHE:
        if path.endswith(".parquet"):
            df = pd.read_parquet(path)
        elif path.endswith(".csv"):
            df = pd.read_csv(path)
        elif path.endswith(".jsonl"):
            df = pd.read_json(path, lines=True)
        else:
            raise ValueError(f"Unsupported silver dataset format: {path}")

        required = {"id", "source_sentences", "silver_indices"}
        missing = required - set(df.columns)
        if missing:
            raise ValueError(f"Missing required silver columns: {missing}")

        _SILVER_CACHE[path] = df

    return _SILVER_CACHE[path]


def normalize_indices(value) -> List[int]:
    """Convert stored indices into a clean, unique, sorted 1-based list.

    Malformed, non-numeric, Boolean, zero, and negative values are ignored
    instead of causing the complete experiment to fail.
    """

    if value is None:
        return []

    # Serialized lists may come from CSV or JSONL files.
    if isinstance(value, str):
        text = value.strip()

        if not text:
            return []

        try:
            value = json.loads(text)
        except (json.JSONDecodeError, TypeError):
            try:
                value = ast.literal_eval(text)
            except (ValueError, SyntaxError):
                return []

    # Support the common sequence forms returned by pandas/parquet readers.
    if not isinstance(value, (list, tuple, set)):
        try:

            if isinstance(value, np.ndarray):
                value = value.tolist()
            else:
                return []
        except ImportError:
            return []

    clean: List[int] = []
    seen = set()

    for item in value:
        # bool is a subclass of int, but True/False should not become 1/0.
        if isinstance(item, bool):
            continue

        try:
            index = int(item)
        except (TypeError, ValueError, OverflowError):
            continue

        if index <= 0 or index in seen:
            continue

        clean.append(index)
        seen.add(index)

    return sorted(clean)


def gold_for_doc(doc) -> List[int]:
    """Return Track C silver labels.

    Called 'gold' only for compatibility with Track A runner/metrics.
    In Track C these are silver indices generated by Track B.
    """
    return normalize_indices(doc["silver_indices"])


def indices_to_text(
    sentences: Sequence[str],
    idxs_1b: Sequence[int],
) -> str:
    """Reconstruct text from valid 1-based sentence indices."""
    clean_indices = normalize_indices(idxs_1b)

    return " ".join(
        str(sentences[index - 1])
        for index in clean_indices
        if index <= len(sentences)
    )

def get_doc_id(doc) -> str:
    return str(doc["id"])


def get_source_sentences(doc) -> List[str]:
    sentences = doc["source_sentences"]

    # Serialized list (CSV/JSONL string form).
    if isinstance(sentences, str):
        try:
            parsed = json.loads(sentences)
        except Exception:
            try:
                parsed = ast.literal_eval(sentences)
            except Exception:
                parsed = None

        if isinstance(parsed, list):
            return [str(s) for s in parsed]

        raise ValueError("source_sentences must be a list or serialized list")

    # Sequence forms returned by pandas/parquet readers (numpy.ndarray,
    # pandas Series expose .tolist()); mirror normalize_indices' handling.
    if hasattr(sentences, "tolist"):
        sentences = sentences.tolist()

    if isinstance(sentences, (list, tuple)):
        return [str(s) for s in sentences]

    raise ValueError("source_sentences must be a list or serialized list")

def get_reference_summary(doc) -> str:
    """Return the abstractive reference, or an empty string when missing."""
    value = doc.get("reference_summary", "")

    if value is None:
        return ""

    try:
        if pd.isna(value):
            return ""
    except (TypeError, ValueError):
        pass

    return str(value).strip()


def cap_from_silver(docs, min_cap: int = 1) -> int:
    """K = median silver sentence count over generated silver dataset.

    Usually this should equal the Track B selected K, e.g. K=4 or K=6,
    but this function is useful if the runner expects a cap.
    """

    counts = [len(gold_for_doc(doc)) for _, doc in docs.iterrows()]
    return max(min_cap, int(np.median(counts) or 0))