"""chain_of_thought — step-by-step whole-document extractive summarization.

Registered twice for the trace ablation:

- chain_of_thought
    One-shot example is answer-only.

- chain_of_thought_trace
    One-shot example includes a cached reasoning trace generated by the
    reference model.

Only the one-shot demonstration differs, so the trace variant remains
one-shot only.
"""

from __future__ import annotations

from typing import Sequence

from ..base import RenderCtx, Shot, Technique
from ..registry import register
from ..shared import reasoning_example_block, render


_NAME = "chain_of_thought"


def _instructions(task: str) -> str:
    """Return Track C chain-of-thought instructions.

    ``task`` is retained for compatibility with the Track A prompt interface.
    Track C should pass ``"summary"``.
    """
    del task

    return (
        "Think step-by-step internally before selecting sentences:\n"
        "1. Identify the document's central topic, event, claim, or development.\n"
        "2. For each sentence, determine what important information it contributes.\n"
        "3. Mark sentences that contain essential facts needed to understand the "
        "whole document.\n"
        "4. Remove sentences that are redundant, overly specific, background-only, "
        "or less important than another sentence expressing the same information.\n"
        "5. Check that the final selection covers the document's main information "
        "without unnecessary repetition.\n"
        "6. Return only the selected sentence indices.\n"
        "Do not include the reasoning in the final output."
    )


def _build(
    sentences: Sequence[str],
    task: str,
    ctx: RenderCtx,
    use_trace: bool,
) -> str:
    """Build either the ordinary or trace-assisted CoT prompt."""
    example_override = (
        reasoning_example_block(
            _NAME,
            task,
            ctx,
        )
        if use_trace
        else ""
    )

    return render(
        task,
        sentences,
        ctx,
        instructions=_instructions(task),
        example_override=example_override,
    )


register(
    Technique(
        name=_NAME,
        build=lambda sentences, task, ctx: _build(
            sentences,
            task,
            ctx,
            False,
        ),
    )
)

register(
    Technique(
        name=f"{_NAME}_trace",
        shots=(Shot.ONE,),
        build=lambda sentences, task, ctx: _build(
            sentences,
            task,
            ctx,
            True,
        ),
    )
)